### ISSUE TITLE
URL resolution/delete other fork

### ISSUE THREAD

**Issue by bmschmidt** [NYU-DH/nyu-dh.github.io#1]
This looks good, and you've made the URL work without backslash which I couldn't figure out. Is the repo name accomplishing that?

Should I just delete the other branch? The only thing that's missing right now is the names of certain never-created pages down more than one step in the hierarchy (e.g., that classroom should include splashes to both my certificate and Lucy's group at FAS.)

**Comment by mnyrop** [comment]
@bmschmidt yep, it's just the repo name. do you want to take a stab at making the certificate and FAS pages? i was assuming those pages could show up as blocks/cards with excerpts on the classroom page that folks could click through and/or you could link to directly. 

as per resources, I think having a single page with link lists (rather than individual pages) should be plenty for now; we could try that with classroom as well to see if it warrants separate pages right away or not...? but totally up to you.

per the other repo, i think that's up to you/the group as well..? if there are important things the other theme has that this one doesn't, we can talk about feature porting.
