### ISSUE TITLE
Finalize Footer content

### ISSUE THREAD

**Issue by mnyrop** [nyu-dh/nyu-dh.github.io#39]

**Comment by coblezc** [comment]
I propose the following for the footer

Should have:
- NYU DH "logo"
- name the 4 units (A&S, Libraries, IT, Center)
- link to NYU Accessibility (https://www.nyu.edu/footer/accessibility.html)
- link to Contact (dh.help@nyu.edu)
- link to Join email list
- link to Join Slack

Optional:
- Copyright statement. The boilerplate seems to be "Unless otherwise noted, all content copyright New York University. All rights reserved."
- link to Privacy policy. cf. https://www.nyu.edu/footer/copyright-and-fair-use/digital-privacy-statement.html, https://nyuhumanities.org/privacy-policy-2/ (an accurate privacy policy would be a good Phase 2 project)
- Search box?
