### ISSUE TITLE
Finalize courses schema

### ISSUE THREAD

**Issue by mnyrop** [nyu-dh/nyu-dh.github.io#47]

**Comment by coblezc** [comment]
Notes to self to add to courses spreadsheet (https://docs.google.com/spreadsheets/d/1nuDt1fchk79-nmWbcWcuQZK1xuZTCxYIy2t0E6a1ABY/edit#gid=0)

done: TRUE if course data is complete/accurate; otherwise FALSE  
pid: formal course number (e.g. DHSS-GA.1121) of course's home dept (don't bother with cross-listed course numbers)  
title: name of course  
semester: season and year when course is offered (e.g. Fall 2022)  
program: department where course is offered; also serves as filter for core course vs. elective course (i.e. DHSS = core; anything else = elective)  
faculty: First Name Last Name (e.g. Ben Schmidt)  
day: day of the week of the course (e.g. Monday)  
time: time of course; unstructured?  
description: what the course is about  
url: link to course site  

Need to decide method for updating courses displayed. Sounds like preference is to include rule in config.yml that displays all courses from the target semester fields.

**Comment by coblezc** [comment]
done. the current design is good - https://nyu-dh.github.io/curriculum/courses/ - and can be used as a mockup of the spreadsheet-generated version

other notes:
-  courses page will display courses for two semesters: the current one and the upcoming one
- the courses spreadsheet (eventually) contain old courses and will be the canonical place for all DH course info. if we later decide to have a 'previously offered courses page', that can easily be pulled from the spreadsheet
